cmip6_models = {
    "CESM2": 0,
    "CNRM-CM6-1-HR": 1,
    "E3SM-1-1": 2,
    "E3SM-2-0": 3,
    "EC-Earth3-Veg": 4,
    "GFDL-ESM4": 5,
    "HadGEM3-GC31-LL": 6,
    "HadGEM3-GC31-MM": 7,
    "KACE-1-0-G": 8,
    "MIROC6": 9,
    "MPI-ESM1-2-HR": 10,
    "MRI-ESM2-0": 11,
    "NorESM2-MM": 12,
    "TaiESM1": 13,
    "Ensemble": 14,
}

cmip6_scenarios = {
    "historical": 0,
    "ssp126": 1,
    "ssp245": 2,
    "ssp370": 3,
    "ssp585": 4,
}

cmip6_vars = [
    "clt",
    "evspsbl",
    "hfls",
    "hfss",
    "pr",
    "prsn",
    "psl",
    "rlds",
    "rsds",
    "sfcWind",
    "siconc",
    "snw",
    "tas",
    "tasmax",
    "tasmin",
    "ts",
    "uas",
    "vas",
]
